# Generated by Django 4.2.7 on 2023-12-03 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_productcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcomment',
            name='comment',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='productcomment',
            name='user_name',
            field=models.CharField(max_length=200),
        ),
    ]
