# Generated by Django 4.2.7 on 2023-12-04 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_productcomment_comment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('email', models.EmailField(max_length=200, verbose_name='Email')),
                ('review_text', models.TextField(verbose_name='Текст отзыва')),
                ('checked', models.BooleanField(default=False, verbose_name='Проверено')),
            ],
        ),
    ]
